# Site wide configuration

title:            Codear — For Web Development Enthusiasts
locale:           es_PE
# url:              http://localhost:4000
url:              http://gianpaima.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Gian Paima
  avatar: bio-photo-4.jpg
  bio: "JesuS. Passionate about front-end development."
  email: giancarlospaima@gmail.com
  disqus-shortname: 'codearpe'
  twitter: gianpaima7
  facebook:
  bing-verify: 'CF4FAF09D209160DA4722728B7945621'
  github: gianpaima
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: gianpaima
  lastfm: #username
  tumblr: #username
  pinterest: gianpaima
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  analytics :
  provider : google
  google : 
      tracking_id : 'UA-56378015-1'

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

